//This is a theme file, please update any theme releated constants here

export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 16,
    FONT_SIZE_20: 20,
    FONT_SIZE_23: 23,
    FONT_SIZE_LARGE: 24,
    FONT_SIZE_EXTRA_LARGE: 32,
    FONT_SIZE_INPUT_FIELD: 17,
    PRIMARY_TEXT_COLOR_LIGHT: '#4A4A4A', // light gray
    PRIMARY_TEXT_COLOR_DARK: '#282828', //dark gray
    SECONDARY_TEXT_COLOR_LIGHT: '#FFFFFF', //white
    SECONDARY_TEXT_COLOR_DARK: "#000000",
    PRIMARY_BACKGROUND_COLOR : '#58a7f9', //dark blue
    SECONDARY_BACKGROUND_COLOR : '#ffc857', //light yellow
    TERTIARY_BACKGROUND_COLOR: '#FFFFFF',
    BACKGROUND_COLOR_D7D7D7: "#D7D7D7",
    PRIMARY_ERROR_TEXT_COLOR: "#DA162E",
    COLOR_DCBA1F: "#DCBA1F",
    COLOR_369799: "#369799",
    COLOR_000000: "#000000",
    COLOR_63C208: "#63C208",
    COLOR_989898: "#989898",
    QUATERNARY_BACKGROUND_COLOR: '#000000',
    PRIMARY_BTN_BACKGROUND_COLOR : '#e74c3c', //light blue
    SECONDARY_BTN_BACKGROUND_COLOR : '#d35400', //dark yellow
    TERTIARY_BTN_BACKGROUND_COLOR : '#000000', //black
    DISABLED_BTN_BACKGROUND_COLOR:'#4A4A4A', //darker gray,
    INPUT_FIELD_BORDER_COLOR: '#E4E4E4',
    INPUT_FIELD_BORDER_COLOR_DARK: '#81868c',
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    DEFAULT_MARGIN: 20,
    DEFAULT_PADDING: 20,
    DEFAULT_SMALL_MARGIN: 10,
    DEFAULT_LARGE_MARGIN: 45,
    DEFAULT_PADDING_BTN: 10,
    PASSWORD_STRONG: '#61C45D', //green
    PASSWORD_MEDIUM: '#FEB809', //yellow
    PASSWORD_WEAK: '#DF5C31', // red
    ROBOTO_REGULAR: 'Roboto-Regular',
    ROBOTO_MEDIUM: 'Roboto-Medium',
    ROBOTO_LIGHT: 'Roboto-Light'
};